= 分享 Spring Boot + Maven

== 事前準備

. JDK: OpenJDK
. IDE: IntelliJ IDEA, Eclipse...

== 認識 Spring Boot

* Spring: 是一種框架，包含一系列的 IoC 容器的設計和依賴注入 (DI) 及整合 AOP 功能。
* Spring Boot 和 Spring MVC 都是框架，它們的核心皆是 Spring。
* Spring Boot 包含了 Spring MVC，同時能簡化配置。

核心功能

. 獨立執行 Spring 專案 +
可以以 jar 包形式獨立執行一個專案，只需透過 java -jar xx.jar。

. 內嵌 servlet 容器 +
內嵌 Tomcat，無須以 war 包形式部署專案。

. 提供 starter 簡化 Maven 配置 *(懶人整合包)* +
以 start pom 來簡化 Maven 的依賴載入，例如：spring-boot-starter-web

. 自動裝配 Spring +
會根據在 Class 路徑中的 jar 包、Class，為 jar 包裡面的 Class 自動配置。

. 準生產的應用監控 +
提供基於 http、ssh、telnet 對執行時的專案進行監控。

. 無程式碼生產和xml配置 +
SpringBoot 不是藉助與程式碼生成來實現的，而是通過條件註解。

== 認識 Apache Maven

. Maven 是一個項目管理和綜合工具，提供構建一個完整的生命周期框架。
. 可以自動完成項目的基礎工具建設，且在非常短的時間裡完成配置工作。
. 項目可重複使用、易維護，同時創建報表、檢查、構建和測試自動化設置。

.Web Project 標準目錄結構
[source,text]
----
├src[程式碼目錄]
│ │
│ ├main[主要目錄]
│ │ │
│ │ ├java[java程式目錄]
│ │ │ │
│ │ │ └[com.example...程式套件目錄]
│ │ │
│ │ ├resources[資源目錄，會copy到編譯路徑，以web來說，會依目錄層級放到WEB-INF/classes下]
│ │ │ │
│ │ │ └[各種資源(設定)檔...]
│ │ │
│ │ └webapp[web目錄]
│ │   │
│ │   └[其它資料…]
│ │
│ └test[測試相關目錄]
│   │
│   ├java[java測試程式目錄]
│   │ │
│   │ └[...]
│   │
│   └resources[測試資源目錄…]
│
└target[各種處理後產生的資料，包含最終生的的打包標的]
----

== Maven Repository

用來存放 Maven 管理的所有 jar 包，分為::

本地倉庫: 本地的 jar 包:::
預設路徑 C:\Users\{User}\.m2\repository

中央倉庫: 官方提供的遠端倉庫:::
https://mvnrepository.com/[MVN Repository]

其它: 自建的倉庫:::
http://repo.tist.com.tw:8081/[台灣資服 Repository]

[NOTE]
====
* 當專案編譯時，Maven 先從本地倉庫中尋找專案所需的 jar 包；若本地倉庫沒有，再到 Maven 的中央倉庫下載。
* Maven 全域設定檔，預設路徑 C:\Users\{User}}\.m2\settings.xml
====

== 使用 IDEA 建立 Maven 專案

IntelliJ IDEA 已經內建了對 Maven 的支援

新專案::
File => New => Project... => 選擇 `Maven`

舊專案轉成 Maven 專案::
對專案點選右鍵 => Add Framework Support... => 勾選 `Maven`

== POM (Project Object Model, 專案物件模型) Reference

pom.xml 是 Maven 的核心，專案需要什麼 jar 包就在 pom.xml 裡面配置。
當編譯專案時 Maven 讀取該檔案，並從倉庫中下載相應的 jar 包。

.新開的專案 pom.xml 基本會長這樣
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> <!--1-->
    <modelVersion>4.0.0</modelVersion> <!--2-->

    <groupId>org.example</groupId>
    <artifactId>test</artifactId>
    <version>1.0-SNAPSHOT</version>
</project>
----
<1> <project>是pom.xml的root element。
<2> POM模型版本

== POM 的關聯

Maven 座標 (Maven Coordinates)::

每一個 artifact 都以 groupId、artifactId 與 version 來做為唯一識別，這三者的組合稱為 Maven Coordinates。 +
用以區別其他的 artifact，指名一個特定 Maven 專案的位置資訊，其作用類似地址

NOTE: artifact 是指一個專案 (project) 建構 (build) 後產生的構件，最常見的就是 jar, war 檔。

* `<groupId>`：通常為組織 domain 名稱，命名方式同 Java 的 package。例如：com.tist。
* `<artifactId>`：通常以專案名稱來命名。
* `<version>`：專案的版本號。

== 依賴 (Dependencies)

依賴傳遞 (Transitive Dependencies)::
如果我們的專案引用了一個 jar 包，而該 jar 包又引用了其他 jar 包，在預設情況下專案編譯時，Maven 會把直接引用和簡潔引用的 Jar 包都下載到本地。

依賴調節 (Dependency mediation)::
為了解決版本不一致的問題 (multiple versions)，並採取就近原則 (nearest definition)。

.Maven 只會引用路徑最短的 D 1.0
[source,text]
----
A
├── B
│   └── C
│       └── D 2.0
└── E
  └── D 1.0
----

.Maven 只會引用路徑最短的 D 2.0
[source,text]
----
A
├── B
│   └── C
│       └── D 2.0
├── E
│   └── D 1.0
│
└── D 2.0
----

依賴管理 (Dependency management)::

繼承 (Inherit):::

.父 pom 配置
[source,xml]
----
<dependencyManagement>
    <dependency>
        <groupId>com.tist</groupId>
        <artifactId>mgov-core</artifactId>
        <version>${mgov-core.version}</version>
    </dependency>
</dependencyManagement>
----

.子 pom 配置
[source,xml]
----
<parent>
    <groupId>com.tist</groupId> <!--1-->
    <artifactId>mgov-cwis-build</artifactId> <!--2-->
    <version>1.0</version> <!--3-->
</parent>
----
<1> 父 pom 所在專案的 groupId
<2> 父 pom 所在專案的 artifactId
<3> 父 pom 所在專案的版本號

模組 (Modules)::
適用於一些比較大的專案，通過合理的模組拆分，實現程式碼的複用，便於維護和管理。

.Example
[source,xml]
----
<modules>
    <module>mgov-share</module>
    <module>mgov-chiayi</module>
    <module>mgov-nantou</module>
</modules>
----

可選依賴 (Optional Dependencies)::
該依賴只能在本專案中傳遞，不會傳遞到引用該專案的父專案中，父專案需要主動引用該依賴才行。

.Example
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>
</dependency>
----

排除依賴 (Excluded Dependencies)::
主動排除子專案傳遞過來的依賴，

.Example
[source,xml]
----
<exclusions>
    <exclusion>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-tomcat</artifactId>
    </exclusion>
</exclusions>
----

依賴範圍 (Dependency Scope)::
控制哪些依賴在哪些 classpath 中可用，哪些依賴包含在一個應用中。

compile （編譯範圍）:::
為預設值，表示此 jar 是所有階段需要的。 +
部署時將一起被打包到jar/war裡面。

test （測試範圍）:::
此 jar 檔只有在測試編譯和測試運行階段才需要使用。如 junit jar 等。 +
部署時將不會打包到 jar/war 裡面。

runtime （運行時範圍）:::
此 jar 檔只有在運行時才需要使用，但在編譯的時候不需要。如 jdbc jar 等， +
而只有在運行的時候才需要 JDBC 驅動實現。

provided （已提供範圍）:::
當運行時，表示此 jar 檔期望由 JDK、Tomcat 及 jboss 等來提供。如 servlet.jar、jsp-api.jar 等。 +
部署時將不會打包到 jar/war 裡面。

system （系統範圍）:::
表示此 jar 檔有系統提供。跟 provided 相似，這是以外部 jar 檔的形式提供，而在 maven repository 是無法找到它的。 +
需指定位置，配合 systemPath 來使用。

.Example
[source,xml]
----
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <scope>test</scope>
</dependency>
----

The Super POM::

* 是 Maven 工具包的一部分，在安裝 Maven 時就有它。
* 新建 Maven 專案時，其專案的 pom.xml 便會自動繼承 Super POM 的設定。
* 其包含一些預設的設定，例如：專案建置 (build) 的目錄位置、原始碼來源目錄位置等。

[NOTE]
====
預設路徑::

C:\Users\{User}\.m2\repository\wrapper\dists\apache-maven-x.x.x-bin\{隨機值}}\apache-maven-3.6.3\lib 內的 +
maven-model-builder-x.x.x.jar\org\apache\maven\model\pom-x.0.0.xml
====

* 從 Super POM 可看到內容定義了：預設的 Central Repository 及 Plugin Central Repository 位置、建置時各目錄位置、預設的 plugin...等。
* 這也說明了為什麼只要在專案的 pom.xml 加入 dependency 後 Maven 便會開始下載 jar 檔至專案的函式庫 (Libraries) 中。

== 最基本的 Spring Boot 配置

.pom.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> <!--1-->
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.4.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.example</groupId>
    <artifactId>test</artifactId>
    <version>0.0.1-SNAPSHOT</version>



</project>
----

lombok

freemarker

== 建構生命週期（Build lifecycle）

三個內建的建構生命週期：Default、Clean 與 Site::

* `Default`: 處理專案部署
* `Clean`: 處理專案資源清除
* `Site`: 處理專案文件

每個建構生命週期中會再分為數個階段（Phase）::

Default 建構生命週期，當中有著以下的階段順序:::

* `validate`：驗證專案正確性以及所有必要資訊已備妥。
* `compile`：編譯專案原始碼。
* `test`：進行單元測試。
* `package`：將相關檔案進行封裝，例如產生JAR檔案。
* `integration-test`：進行整合測試。
* `verify`：驗證檔案封裝是否正確。
* `install`：將封裝的檔案安裝至本地倉庫（Local repository）。
* `deploy`：部署檔案。

每個階段可以使用 mvn 指令搭配階段名稱呼叫，這些階段必須按照順序進行::
Example::: Execute Maven Goal => `mvn compile`

http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference[Default Lifecycle]

== 打包成可部署到 Server 上的 war 檔

增加 `<packaging>war</packaging>`

.pom.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> <!--1-->
  ...
  <packaging>war</packaging> <!--1-->
  ...
</project>
----
<1> 預設是 .jar 檔

== 打包成可執行的 jar 檔

又稱 fat jar ，是包含所有第三方依賴的 jar 包，jar 包中嵌入了除 java 虛擬機以外的所有依賴，是一個 all-in-one jar 包。

.fat jar 目錄結構
[source,text]
----
├─BOOT-INF │
├─classes │
└─lib
├─META-INF
│ ├─maven
│ ├─app.properties
│ ├─MANIFEST.MF
└─org
└─springframework
└─boot
└─loader
├─archive
├─data
├─jar
└─util
----

一般 Java 應用:


Web Service:

== 常用指令

查閱 Maven 版本::
`mvn help:evaluate -Dexpression=project.version`

在程式發佈前，可檢查是否有更新的版本存在

檢查使用的函式庫有那些更新的版本::
`mvn versions:display-dependency-updates`

檢查使用的 Plugin 有那些更新的版本::
`mvn versions:display-plugin-updates`